# Generated by Django 5.2.5 on 2025-11-04 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_linea1', models.CharField(max_length=255)),
                ('direccion_linea2', models.CharField(blank=True, max_length=255, null=True)),
                ('Colonia', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('etiqueta', models.CharField(blank=True, max_length=50, null=True)),
                ('entrega', models.CharField(choices=[('Encontrarse', 'Encontrarse'), ('Dejar en puerta', 'Dejar en puerta')], default='Encontrarse', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
        ),
    ]
